### ISSUE TITLE
[enhancement] improve the elections simulator

### ISSUE THREAD

**Issue by betich** [PED4you/ped4you-website#1]
# Tasks

- [ ] write custom date picker ui
- [x] add github link to footer
- [x] minor ui fixes

## Write a custom calendar

The current calendar is from a random react library i found and it has some problems (notably when you choose the year in the picker, the year is displayed in ค.ศ. but it should be displayed in พ.ศ.). The library also opts in system-ui based theme picking, which is not intended.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/28398789/235475411-14b5f56c-0c58-426f-9489-86d63e3e0515.png">

## The ui is quite janky, in some parts. These are some notable issues:

1. In the <ReceiveCard /> page (8), some mobile ui is janky for the "แตะเพื่อลงลายมือชื่อ" button
<img width="290" alt="image" src="https://user-images.githubusercontent.com/28398789/235476161-e527ffc3-048c-4c78-ac84-91b493933986.png">

2. In some cases, the circle is not in the center of the image (4)
![image](https://user-images.githubusercontent.com/28398789/235476401-813b70f9-db95-4e35-8c9f-0acb9173e56f.png)

**Comment by betich** [comment]
pull requests are welcome btw
